baseurl = "https://StackSquirrel.github.io/"
languageCode = "en-us"
title = "Readers' Advisory blog"
theme = "hugo-cards"
paginate = 6

[params]
  builtBy = "Donna MacLeod"
  defaultImage = "gopher.jpg"

  facebook = ""
  quora = ""
  twitter = "https://twitter.com/thepsammead"
  github = "https://github.com/StackSquirrel"
  email = "info@dmacleod.ca"
  rss = "https://StackSquirrel.github.io/index.xml"
  instagram = "https://www.instagram.com/laddiethedog/"

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""
  disqus = ""

  [params.copyright]
     name = "Donna MacLeod"
     link = "https://dmacleod.ca/"

